<a href="https://colab.research.google.com/github/RaviGprec/NLP/blob/master/What_happens_when_our_model_sees_new_words(which_were_not_part_present_in_training_set)_while_predicting_%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Understanding of Bag of Words**

In [56]:
import numpy as np
import pandas as pd
import nltk
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

text  = [["movies is good","positive"],
            ["movie is not good","negative"]
            ]
df = pd.DataFrame(text, columns = ["review",'sentiment'])
df.head()

review sentiment
0     movies is good  positive
1  movie is not good  negative

In [57]:
cv = CountVectorizer(stop_words=frozenset(["is"])) #Here I gave stop_words is Only "is" becuase if we use stop_words='english' not will not be considered. Hence gave only "is" to be considered as stop_word
X_transform = cv.fit_transform(df['review']).toarray()
df_1 = pd.DataFrame(X_transform,columns=cv.get_feature_names())
df_1.head()

good  movie  movies  not
0     1      0       1    0
1     1      1       0    1

This is the matrix of Bag-Of-Words which is created by our CountVectorizer. The main intension of creating this example is to answer the question 'what happens when our model encounters unseen words in the training set (i.e how the model predicts when it sees new words which were not present in trainin set)?'

Let's train the model first

In [0]:
model = MultinomialNB().fit(df_1,df['sentiment'])


Now, our model can predict the sentiment when we give test data with the words (good, movie, movies, not). 

In [59]:
test = ['good not movie']
test_1 = cv.transform(test).toarray()
print(test_1)
print(model.predict(test_1))

test = ['good movies']
test_1 = cv.transform(test).toarray()
print(test_1)
print(model.predict(test_1))

[[1 1 0 1]]
['negative']
[[1 0 1 0]]
['positive']


So far it is good. What happens when we give new words (unseen words). How the BOW (bag of words) matrix will look like?

In [60]:
test = ['good hello']
test_1 = cv.transform(test).toarray()
print(test_1)
test_1 = pd.DataFrame(test_1,columns=cv.get_feature_names())
test_1

[[1 0 0 0]]


good  movie  movies  not
0     1      0       0    0

countvectorizer considered only "good" and it ignored "hello". So the conclusion is that countvectozer considers only the ones which it has seen and for rest of the words it ignores them.

In [61]:
print(model.predict(test_1))

['positive']
